# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- citest

pool:
  name: 'DLTS-Platform'

# container: ubuntu:18.04

variables: { SUBSCRIPTION_NAME: "'Bing DLTS'"}

steps:
- script: |
    cd src/ClusterBootstrap/
    az account set --subscription $(SUBSCRIPTION_NAME)
  displayName: 'Set Subscription'

- script: |
    cd src/ClusterBootstrap/scripts
    CONFIG_TYPE="${CONFIG_TYPE:-cpu}"
    ./set_config.sh $CONFIG_TYPE
    cd ..
    ./bash_step_by_step_deploy.sh
  displayName: 'Deploy DLWorkspace'

- script: |
    cd src/ClusterBootstrap/
    USER=$(grep -B3 admin_username cluster.yaml | awk '{print $2}')
    CONFIG_TYPE="${CONFIG_TYPE:-cpu}"
    cd scripts
    ./timed_check.sh 5 30 ./pscp_role.sh worker check_machine.sh /home/${USER}
    ./timed_check.sh 5 30 ./pssh_role.sh worker \"bash check_machine.sh $CONFIG_TYPE\"

    ./timed_check.sh 5 30 ./check_node_ready.sh infra
    ./timed_check.sh 5 30 ./pscp_role.sh infra check_docker_ready.sh /home/${USER}
    ./timed_check.sh 5 30 ./pssh_role.sh infra \"bash ./check_docker_ready.sh infra\"

    ./timed_check.sh 5 30 ./check_node_ready.sh worker
    ./timed_check.sh 5 30 ./pscp_role.sh worker check_docker_ready.sh /home/${USER}
    ./timed_check.sh 5 30 ./pssh_role.sh worker \"bash ./check_docker_ready.sh worker\"

    ./timed_check.sh 5 30 ./pssh_role.sh worker \"bash ./check_docker_ready.sh postlbl\"
    ./timed_check.sh 10 30 ./pssh_role.sh infra \"bash check_docker_ready.sh services\"
  displayName: 'Verify deployment'

- script: |
    echo TODO: RUN functional tests!
  displayName: 'Functional tests'

- script: |
    cd src/ClusterBootstrap/
    RESOURCEGRP=$(grep cluster_name cluster.yaml|awk '{print $2}')ResGrp
    az group delete --name $RESOURCEGRP --yes
  displayName: 'Cleanup'
